version: '3'

services:
  listener:
    container_name: al1-notifications-listener
    image: romainlenoir/al1-notifications:latest
    env_file:
      - .docker/listener.env
    links:
      - api_mail
    restart: always

  api_mail:
    container_name: al1-notifications-apimail
    image: esgimicroci/al1-notifications
    env_file:
      - .docker/api_mail.env
    ports:
      - '80:80'
    expose:
      - '80'
    links:
      - mysql
    restart: always

  mysql:
      image: mysql:latest
      command: "--default-authentication-plugin=mysql_native_password"
      container_name: al1-notifications-mysql
      volumes:
          - .docker/volume:/var/lib/mysql
      env_file:
          - .docker/mysql.env
      expose:
          - 3306
      restart: always

volumes:
  rabbitmq_data:
    driver: local